---
title: "Callback 지옥, Promise"
tags: [javascript]
categories:
  - js
date: 2023-03-28
toc : true
---

- Javascript는 Synchronous --> hoisting(var나 함수 선언이 제일 위로 올라가는 것)이 된 시점 부터, 하나 하나 순차적으로 실행


```javascript

//1 -> 3 -> 2 로 출력 됨
console.log('1');
setTimeout(()=> console.log('2'), 1000);
console.log('3');

//Synchronous callback
function printImmediately(print){print();}
printImmediately(()=> console.log('hello')) //1 -> 3 -> hello -> 2

//Asynchronous callback
function printWithDelay(print, timeout){
  setTimeout(print, timeout);
};
printWithDelay(()=> console.log('async callback'), 2000); // 1, 3, hello, 2, async callback

```

### callback 지옥

- 가독성이 떨어짐, 디버깅이 어려움
```javascript
class UserStorage{
  loginUser(id, password, onSuccess, onError) {
    setTimeout(() => {
      if(
        (id ==='tame'&& password ==='1') ||
        (id ==='choi'&& password ==='2')
      ){
        onSuccess(id);
      }
      else{
        onError(new Error('not found'));
      }
    }, 2000)
  }

  getRoles(user, onSuccess, onError){
    setTimeout(()=> {
      if (user ==='taem'){
        onSuccess({name:user, role:'admin'});
      }
      else{
        onError(new Error('not access'));
      }
    }, 1000)
  }
}

const userStorage = new UserStorage();
const id = prompt('enter id')
const password = prompt('enter pw')
userStorage.loginUser(
  id,
  password,
  user => {
    userStorage.getRoles(
      user, 
      userWithRole => {
        alert(`hello {$userWithRole.name} role {$userWithRole.role}`);
      },
      error => {
        console.log(error);
      });
  },
  error => {
    console.log(error);
      });
)
```

### Callback 지옥 극복 -> PROMISE
#### 1.Promise
- JS에서 제공하는 비동기를 간편하게 처리할 수 있는 object
- EX) 준비중인 코스가 있는데 관심있는 사람은 미리 등록할 수 있는 시스템 가짐, 사전 등록신청 해놓으면 수업이 오픈되면 등록 완료 메일을 보내줌
- state / producer와 consumer의 차이 요게 중요
    - state : pending(promise 진행 중) -> fulfilled(완료) or rejected(실패)
    - Producer, Consumer
```javascript
//Producer
//새로운 promise가 만들어지면, executer 콜백함수는 자동으로 실행됨
const promise = new Promise((resolve, reject) =>{
  //doing sonme heavy work
  console.log('doning somthing');
  setTimeout(()=>{
    // resolve('taem');
    reject(new Error('no network'));
  }, 2000)
});

//Counsumer
// then, catch, finally를 활용
promise
  .then(value => {
    console.log(vlaue); //taem이 나옴, promise가 정상정으로 수행됬을 때, resolve 콜백함수를 통해 아규먼트로 전달된 값
    })
  .catch(error => {
    console.log(error);
  })
  .finally(()=> console.log('end promise');)


//Promise chaining
const fetchNumber = new Promise((resolve, reject) => {
  setTimeout(()=> resolve(1), 1000);
})

fetchNumber
.then(num => num*2)
.then(num => num*3)
.then(num => {
  return new Promise((resolve, reject) =>{
    setTimeout{() => resolve(num -1), 1000};
  });
})
.then(num => console.log(num)); //5


//Error handling
const getHen = (() => new Promise((resolve,reject) => {
  setTimeout() => resolve('닭'), 1000});
)

const getEgg = ( hen => new Promise((resolve,reject) => {
  setTimeout() => resolve(`${hen} => '계란'`), 1000});
)

const cook = ( egg => new Promise((resolve,reject) => {
  setTimeout() => resolve(`${egg} => '후라이'`), 1000});
)

getHen()
.then(hen =>getEgg(hen))
.then(egg => cook(egg))
.then(meal => console.log(meal));

getHen() 
.then(getEgg)
.catch(error =>{
  return '소시지'
})
.then(cook)
.then(console.log);
.finally(console.log('End cook'))
```


#### Callback 지옥 극복
```javascript
class UserStorage{
  loginUser(id, password) {
    return new Promise((resolve, reject) =>
    setTimeout(() => {
      if(
        (id ==='tame'&& password ==='1') ||
        (id ==='choi'&& password ==='2')
      ){
        resolve(id);
      }
      else{
        reject(new Error('not found'));
      }
    }, 2000));
  }

  getRoles(user){
    return new Promise((resolve, reject) =>{
      setTimeout(()=> {
        if (user ==='taem'){
          resolve({name:user, role:'admin'});
        }
        else{
          reject(new Error('not access'));
        }
      }, 1000)
      })
  }
}

const userStorage = new UserStorage();
const id = prompt('enter id')
const password = prompt('enter pw')
userStorage.loginUser(id, password)
.then(user => getRoles)
.then(user => alert(`Hello ${user.name}`))
.catch(console.log)
```